### ISSUE TITLE
AttributeError: 'GraphsTuple' object has no attribute 'device' when running with `data='WindGraph'`

### ISSUE THREAD

**Issue by David--K** [LarsBentsen/FFTransformer#13]
Hi, first thanks a lot for providing all your findings with us, this is super beneficial!  I'm, trying to train the model for a WindGraph, I used the plain code from your repository and changed the `--data` parameter to `WindGraph`. I run with `Python 3.6.13` and I had to use different versions for the following dependencies: 
```
torch==1.10.2+cu113
torchaudio==0.10.2+cu113
torchvision==0.11.3+cu113
```

When I try to start the training with `python run.py` I get the following error:
```bash
$ python run.py 
Args in experiment:
Namespace(activation='gelu', all_stations=0, batch_size=32, c_out=1, checkpoint_flag=1, checkpoints='./checkpoints/', d_ff=2048, d_layers=1, d_model=512, data='WindGraph', data_path='wind_data.csv', data_step=1, dec_in=8, des='test', devices='0,1', distil=True, dropout=0.05, e_layers=2, embed='timeF', enc_in=8, factor=3, features='M', freq='10min', gnn_layers=2, gpu=0, is_training=1, itr=1, kernel_size=3, label_len=48, learning_rate=0.001, loss='mse', lr_decay_rate=0.8, lradj='type1', min_num_nodes=2, mlp_out=0, model='FFTransformer', model_id='test', moving_avg=25, n_closest=None, n_heads=8, norm_out=1, num_decomp=4, num_workers=0, output_attention=False, patience=5, plot_flag=1, pred_len=6, qk_ker=4, res_len=None, root_path='./dataset_example/WindData/dataset/', seq_len=64, sparse_flag=1, target='KVITEBJØRNFELTET', test_dir='', top_keys=0, train_epochs=10, train_strat_lstm='recursive', use_gpu=True, use_multi_gpu=False, v_conv=0, verbose=1, win_len=6)
Use GPU: cuda:0
>>>>>>>start training : test_FFTransformer_WindGraph_ftM_sl64_ll48_pl6_0>>>>>>>>>>>>>>>>>>>>>>>>>>
Could not load best model
Updating learning rate to 0.001
Traceback (most recent call last):
  File "run.py", line 150, in <module>
    main()
  File "run.py", line 125, in main
    exp.train(setting)
  File "/xxx/FFTransformer_plain/exp/exp_main.py", line 281, in train
    teacher_forcing_ratio=teacher_forcing_ratio, batch_y=batch_y)
  File "/xxx/miniconda3/envs/fftransformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xxx/FFTransformer_plain/models/FFTransformer.py", line 100, in forward
    x_enc_freq, x_enc_trend = get_wt(x_enc, num_decomp=self.num_decomp)
  File "/xxx/FFTransformer_plain/layers/WaveletTransform.py", line 6, in get_wt
    dwt_for = DWT1DForward(J=num_decomp, mode='symmetric', wave='db4').to(x.device)
AttributeError: 'GraphsTuple' object has no attribute 'device'
```
Could you please provide any guidance that might help me solve this issue? I appreciate any help you can offer.

**Comment by LarsBentsen** [comment]
Hi David, 
I'm glad to hear that you're enjoying the repo and apologies for the very late response.
I assume that you're using graph-based data for spatio-temporal forecasting? If so, I believe you should use the "GraphFFTransformer", not the "FFTransformer" which you seem to be using in your code. 
Could you test this and let me know how you get on?
